version: '3'

services:

  master:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=4M
    hostname: master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_HOST: master
    ports:
      - "13306:3306"
  slave:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=128M
    hostname: slave
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_HOST: slave
    ports:
      - "13307:3306"
  proxysql:
    build:
      dockerfile: Dockerfile-proxysql
      context: .
    entrypoint: /bin/bash -c 'while [ 1 ]; do /usr/bin/proxysql -f -D /var/lib/proxysql -d -c /etc/proxysql.cfg; done'
    environment:
      - PROXYSQL_DATADIR='/var/lib/proxysql'
      - PROXYSQL_USERNAME='admin'
      - PROXYSQL_PASSWORD='admin'
      - PROXYSQL_HOSTNAME='127.0.0.1'
      - PROXYSQL_PORT='6032'
      - CLUSTER_USERNAME="monitor"
      - CLUSTER_PASSWORD="monitor"
    volumes:
      - ${PWD}/proxysql.cfg:/etc/proxysql.cfg
    ports:
      - "16032:6032"
      - "16033:6033"
      - "16080:6080"
    depends_on:
      - master
      - slave


